### ISSUE TITLE
Gnome 3.32: Icon distorted, height too large

### ISSUE THREAD

**Issue by sebastien** [insynchq/insync-gnome-extension#1]
Since Gnome 3.32 (Fedora 30), the Insync gnome extension has an incorrect icon height:

![image](https://user-images.githubusercontent.com/14598/57455661-a1841100-7239-11e9-9d42-49a986df8c1e.png)

This makes the right icons bar higher than required and makes the charts bleed out.

**Comment by oscarbranson** [comment]
Bump.

Any sight of a fix for this?

**Comment by oscarbranson** [comment]
Seriously? No response from devs since 9th May and this is a paid service? Expecting better.

**Comment by sebastien** [comment]
Maybe we should contact them on the forum instead.

Edit: Here's the [link](https://forums.insynchq.com/t/gnome-status-icon-too-large/14556)

**Comment by oscarbranson** [comment]
Just emailed them to highlight the issue and ask for a response.

**Comment by kurtkerwinko** [comment]
Hi @sebastien and @oscarbranson 
Sorry for the late response! This is no longer maintained. You can remove this Gnome extension and install [this](https://extensions.gnome.org/extension/615/appindicator-support/) extension instead. After a reboot, the Insync tray icon should show up if Insync is running.

**Comment by oscarbranson** [comment]
Thanks @kurtkerwinko!

It would be very useful if this was mentioned in the description of the Insync extension on the Gnome 3 extensions page.

**Comment by sebastien** [comment]
Hey @oscarbranson, did that work for you? I just tried it and the Insync icon does not show up. Let me know how it goes for you.

**Comment by kurtkerwinko** [comment]
Hi @sebastien 
What distro / version are you using? Also what desktop environment?

**Comment by sebastien** [comment]
@kurtkerwinko I'm on Fedora 30/Gnome 3.32.2 -- but trying to enable the extension again I get  a dialog with the following message `Unable to find "appindicatorsupport_rgcjonas.gmail.com"`.

**Comment by kurtkerwinko** [comment]
@sebastien Hmm, there may be an issue when the extension was being installed. Tried it out on my `Fedora 30/Gnome 3.32.2` and it works. Can you walk me through on how you installed the extension?

**Comment by sebastien** [comment]
@kurtkerwinko OK, so it's working now. I upgraded the distro, reinstalled the extension and it's now working like a charm. Thanks!
